### PR TITLE
Made changes to README.md to reflect some prerequisites.

### PR DESCRIPTION
**Pull request by SonnyRajagopalan**
I'd like to submit a pull request for my `README.md` changes (IAM policies prerequisite).

### CODE REVIEW

**Comment by zhangzhx** [comment]
Does the change agree with Apache 2 License?

**Comment by SonnyRajagopalan** [comment]
I am not sure exactly what you mean. If you are asking if my changes are consistent with the SDK's overall license, I am OK with that.

**Comment by manikandanrs** [comment]
Yes. We just want to make sure you submit this under Apache 2.0 license.

**Comment by SonnyRajagopalan** [comment]
Again, I have no idea how to do that. Is this a matter of just saying "Yes,
I agree with the terms of the Apache 2.0 License?" Is there any issue with
that?

**Comment by manikandanrs** [comment]
That all we need. We just need a comment saying that to keep legal happy.

**Comment by zhangzhx** [comment]
Yes, we just need something like a verbal agreement that you are submitting the code under Apache 2.0 license. I will ask for approval from our open source team to make sure there is no legal issue before merging the pull request.

**Pull request merged**
